# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'install dependencies'
- script: npm run lint
  displayName: 'run linting'
- script: npm test
  displayName: 'run tests'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    app_build_command: 'npm run build'
    output_location: 'dist/angular-aswa'
    api_location: 'api'
    api_build_command: 'npm run build'
    azure_static_web_apps_api_token: $ASWA_DEPLOYMENT_TOKEN
    deployment_environment: 'test'
    production_branch: 'main'
