options:
  docker: true
  size: 2x

pipelines:
  branches:
    main:
      - step:
          name: Deploy to test
          deployment: test
          size: 2x
          services:
            - docker
          script:
            - pipe: microsoft/azure-static-web-apps-deploy:main
              variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                APP_BUILD_COMMAND: 'npm run build'
                API_LOCATION: 'api'
                API_BUILD_COMMAND: 'npm run build'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/dist/aswa-angular'
                API_TOKEN: $deployment_token

definitions:
  services:
    docker:
      memory: 4096
